package model;
// Generated May 29, 2022 9:16:32 PM by Hibernate Tools 4.3.1



/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien  implements java.io.Serializable {


     private Integer ma;
     private String ten;
     private boolean phai;
     private String lop;
     private double diem;

    public Sinhvien() {
    }

    public Sinhvien(String ten, boolean phai, String lop, double diem) {
       this.ten = ten;
       this.phai = phai;
       this.lop = lop;
       this.diem = diem;
    }
   
    public Integer getMa() {
        return this.ma;
    }
    
    public void setMa(Integer ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public boolean isPhai() {
        return this.phai;
    }
    
    public void setPhai(boolean phai) {
        this.phai = phai;
    }
    public String getLop() {
        return this.lop;
    }
    
    public void setLop(String lop) {
        this.lop = lop;
    }
    public double getDiem() {
        return this.diem;
    }
    
    public void setDiem(double diem) {
        this.diem = diem;
    }




}


